// packages/studio/src/lib/components/book/BookOutline.svelte
<script>
  let { bookId, book } = $props();
  let outline = $derived(book?.outline || { volumes: [], progress: { mainPlot: 0 } });
  let expanded = $state({});

  function toggle(i) { expanded[i] = !expanded[i]; expanded = { ...expanded }; }
</script>

<div class="space-y-4">
  <div class="border border-border p-4">
    <div class="flex items-center justify-between mb-2">
      <p class="text-[10px] uppercase tracking-widest text-muted">主线进度</p>
      <span class="font-mono text-sm">{Math.round((outline.progress?.mainPlot || 0) * 100)}%</span>
    </div>
    <div class="w-full h-1.5 bg-border/30 rounded-full overflow-hidden">
      <div class="h-full bg-foreground/40 transition-all" style="width: {(outline.progress?.mainPlot || 0) * 100}%"></div>
    </div>
  </div>

  {#if outline.volumes?.length === 0}
    <div class="border border-border text-center py-8">
      <p class="text-sm text-muted">暂无大纲</p>
      <p class="text-xs text-muted mt-1">通过「写作」Tab 或 AI 对话创建大纲</p>
    </div>
  {:else}
    {#each outline.volumes || [] as vol, vi}
      <div class="border border-border">
        <button onclick={() => toggle(vi)} class="w-full text-left px-4 py-3 flex items-center justify-between text-sm hover:bg-foreground/5 transition-colors">
          <span class="font-serif">{vol.title || `卷 ${vi + 1}`}</span>
          <span class="text-muted text-xs">{expanded[vi] ? '−' : '+'}</span>
        </button>
        {#if expanded[vi]}
          <div class="px-4 pb-3 border-t border-border">
            {#each vol.chapters || [] as ch, ci}
              <div class="py-2 border-b border-border/50 last:border-0 text-xs text-muted">
                <span class="text-foreground/50 mr-2">{ci + 1}</span>{ch.title || `章节 ${ci + 1}`}
              </div>
            {/each}
          </div>
        {/if}
      </div>
    {/each}
  {/if}
</div>

// packages/studio/src/components/book/BookOutline.tsx
'use client';

import { useState } from 'react';

export function BookOutline({ bookId, book }: { bookId: string; book: any }) {
  const outline = book.outline || { volumes: [], progress: { mainPlot: 0 } };
  const [expanded, setExpanded] = useState<Record<number, boolean>>({});

  return (
    <div className="space-y-6">
      <div className="card-editorial">
        <div className="flex items-center justify-between mb-4">
          <p className="label-editorial text-muted">主线进度</p>
          <span className="font-mono text-sm">{Math.round((outline.progress?.mainPlot || 0) * 100)}%</span>
        </div>
        <div className="w-full h-2 bg-border">
          <div className="h-2 bg-foreground" style={{ width: `${(outline.progress?.mainPlot || 0) * 100}%` }} />
        </div>
      </div>

      {outline.volumes.length === 0 ? (
        <div className="card-editorial text-center py-12">
          <p className="text-muted mb-3">暂无大纲</p>
          <p className="text-xs text-muted">通过「写作」Tab 或 Agent 对话创建大纲</p>
        </div>
      ) : (
        <div className="space-y-4">
          {outline.volumes.map((vol: any, vi: number) => (
            <div key={vi} className="card-editorial">
              <button
                onClick={() => setExpanded({ ...expanded, [vi]: !expanded[vi] })}
                className="w-full text-left flex items-center justify-between"
              >
                <div>
                  <span className="font-mono text-xs text-muted mr-2">卷{vol.volumeNumber || vi + 1}</span>
                  <span className="font-serif">{vol.title || '未命名'}</span>
                </div>
                <span className="text-muted text-sm">{expanded[vi] ? '−' : '+'}</span>
              </button>
              {expanded[vi] && (
                <div className="mt-4 pt-4 border-t border-border space-y-2">
                  <p className="text-sm text-muted">{vol.summary}</p>
                  {vol.chapters?.map((ch: any, ci: number) => (
                    <div key={ci} className="flex items-center gap-3 py-2 px-3 border border-border text-sm">
                      <span className="font-mono text-xs text-muted w-8">第{ch.chapterNumber}章</span>
                      <span className="flex-1">{ch.title || ch.summary?.substring(0, 30)}</span>
                      <span className={`text-xs px-2 py-0.5 ${ch.status === 'completed' ? 'bg-green-100 text-green-800' : 'bg-muted/20 text-muted'}`}>{ch.status}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
