// packages/studio/src/lib/components/book/BookConstraints.svelte
<script>
  import { api } from '$lib/api';
  import { toasts } from '$lib/stores/toast';
  let { bookId } = $props();
  let files = $state([]);
  let selected = $state(null);
  let content = $state('');
  let loading = $state(true);

  async function loadFiles() {
    try { const data = await api.get(`/api/books/${bookId}/constraints`); files = data.files || []; } catch {}
    loading = false;
  }
  loadFiles();

  async function selectFile(name) {
    selected = name;
    try { const data = await api.get(`/api/books/${bookId}/constraints?file=${name}`); content = data.content || ''; } catch {}
  }

  async function saveContent() {
    if (!selected) return;
    try { await api.put(`/api/books/${bookId}/constraints`, { name: selected, content }); toasts.add('已保存', 'success'); } catch { toasts.add('保存失败', 'error'); }
  }

  async function createFile() {
    const name = prompt('文件名（如 writing-guide.md）');
    if (!name) return;
    try { await api.post(`/api/books/${bookId}/constraints`, { name, content: '' }); await loadFiles(); selectFile(name); } catch {}
  }
</script>

<div class="flex gap-4">
  <div class="w-40 flex-shrink-0 space-y-1">
    <div class="flex items-center justify-between mb-2"><p class="text-[10px] uppercase tracking-widest text-muted">约束文件</p><button onclick={createFile} class="text-xs text-muted hover:text-foreground">+</button></div>
    {#each files as f}
      <button onclick={() => selectFile(f.name)} class="w-full text-left px-2 py-1.5 text-xs transition-colors {selected === f.name ? 'bg-foreground/10 text-foreground' : 'text-muted hover:text-foreground hover:bg-foreground/5'}">{f.name}</button>
    {/each}
  </div>
  <div class="flex-1 min-w-0">
    {#if selected}
      <textarea bind:value={content} class="w-full border border-border p-4 font-mono text-xs bg-transparent h-80 resize-none focus:outline-none focus:border-foreground"></textarea>
      <button onclick={saveContent} class="mt-2 bg-foreground text-background px-3 py-1.5 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors">保存</button>
    {:else}
      <p class="text-xs text-muted text-center py-16">选择左侧文件进行编辑</p>
    {/if}
  </div>
</div>

// packages/studio/src/components/book/BookConstraints.tsx
'use client';

import { api } from '@/lib/api';

import { useState, useEffect } from 'react';

interface ConstraintFile {
  name: string;
  size: number;
  preview: string;
}

export function BookConstraints({ bookId }: { bookId: string }) {
  const [files, setFiles] = useState<ConstraintFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  // Load file list
  useEffect(() => {
    api.get(`/api/books/${bookId}/constraints`).then(data => {
      setFiles(data.files || []);
      if (data.files?.length > 0 && !selectedFile) {
        setSelectedFile(data.files[0].name);
      }
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [bookId]);

  // Load file content when selected
  useEffect(() => {
    if (!selectedFile) return;
    api.get(`/api/books/${bookId}/constraints?file=${selectedFile}`)
      .then(data => {
        setContent(data.content || '');
        setSaved(false);
      });
  }, [selectedFile, bookId]);

  const handleSave = async (file?: string, data?: string) => {
    const saveFile = file || selectedFile;
    const saveContent = data !== undefined ? data : content;
    if (!saveFile) return;
    setSaving(true);
    await api.put(`/api/books/${bookId}/constraints`, { name: saveFile, content: saveContent });
    setSaving(false);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  // Auto-save every 30 seconds
  useEffect(() => {
    if (!selectedFile || !content) return;
    const timer = setInterval(() => {
      handleSave(selectedFile, content);
    }, 30000);
    return () => clearInterval(timer);
  }, [selectedFile, content]);

  const handleCreateFile = async () => {
    const name = prompt('约束文件名称（英文，如 character-rules）');
    if (!name) return;
    await api.post(`/api/books/${bookId}/constraints`, { name, content: '' });
    const data = await api.get(`/api/books/${bookId}/constraints`);
    setFiles(data.files || []);
    setSelectedFile(name.replace(/[^a-zA-Z0-9_-]/g, '_') + '.md');
  };

  const handleDeleteFile = async (fileName: string) => {
    if (!confirm(`确定删除 ${fileName}？`)) return;
    await api.del(`/api/books/${bookId}/constraints`, { name: fileName });
    const data = await api.get(`/api/books/${bookId}/constraints`);
    setFiles(data.files || []);
    if (selectedFile === fileName) {
      setSelectedFile(data.files?.[0]?.name || null);
    }
  };

  if (loading) return <div className="text-muted text-sm">加载中...</div>;

  const fileLabels: Record<string, string> = {
    'style-constraints.md': '风格约束',
    'genre-constraints.md': '题材约束',
    'character-rules.md': '角色规则',
    'plot-constraints.md': '剧情约束',
    'banned-words.md': '禁词列表',
    'writing-guide.md': '写作指南',
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-serif text-lg">约束文件</h3>
          <p className="text-xs text-muted mt-1">编辑写作约束，Agent会读取这些文件来指导创作</p>
        </div>
        <button onClick={handleCreateFile} className="btn-editorial-primary text-xs">新建约束文件</button>
      </div>

      <div className="flex gap-6">
        {/* File List */}
        <div className="w-56 flex-shrink-0 space-y-1">
          {files.map(f => (
            <button
              key={f.name}
              onClick={() => setSelectedFile(f.name)}
              className={`w-full text-left px-3 py-2 text-sm transition-colors flex items-center justify-between ${
                selectedFile === f.name
                  ? 'bg-foreground text-background'
                  : 'hover:bg-foreground/5'
              }`}
            >
              <span className="truncate">{fileLabels[f.name] || f.name}</span>
              <button
                onClick={(e) => { e.stopPropagation(); handleDeleteFile(f.name); }}
                className="text-xs opacity-50 hover:opacity-100"
              >
                ✕
              </button>
            </button>
          ))}
        </div>

        {/* Editor */}
        {selectedFile ? (
          <div className="flex-1 flex flex-col">
            <div className="flex items-center justify-between mb-3">
              <span className="font-mono text-sm text-muted">{selectedFile}</span>
              <div className="flex items-center gap-3">
                <span className="text-xs text-muted">{content.length} 字符</span>
                <button onClick={() => handleSave()} disabled={saving} className={`btn-editorial-primary text-xs ${saving ? 'opacity-50' : ''}`}>
                  {saving ? '保存中...' : saved ? '已保存 ✓' : '保存'}
                </button>
              </div>
            </div>
            <textarea
              value={content}
              onChange={e => { setContent(e.target.value); setSaved(false); }}
              className="flex-1 w-full p-4 font-mono text-sm leading-relaxed border border-border focus:outline-none focus:border-foreground resize-none bg-background"
              placeholder="在此编辑约束内容..."
              spellCheck={false}
            />
          </div>
        ) : (
          <div className="flex-1 flex items-center justify-center text-muted text-sm border border-border">
            选择左侧文件进行编辑
          </div>
        )}
      </div>
    </div>
  );
}
