// packages/studio/src/routes/(app)/store/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { isTauri, tauriInvoke } from '$lib/tauri';
  import { toasts } from '$lib/stores/toast';
  import { api } from '$lib/api';

  let templates = $state([]);
  let loading = $state(true);
  let activeCategory = $state('all');
  let showExport = $state(false);
  let showClone = $state(false);
  let books = $state([]);
  let exportBookId = $state('');
  let exportName = $state('');
  let exportDesc = $state('');
  let cloneUrl = $state('');
  let status = $state('');

  const CATEGORIES = [
    { id: 'all', label: '全部' },
    { id: 'template', label: '项目模板' },
    { id: 'style', label: '风格包' },
    { id: 'constraint', label: '约束规则' },
  ];

  const officialTemplates = [
    { name: '仙侠·废柴逆袭', repo: 'https://github.com/Cola-Pig1121/conovel-templates', description: '仙侠题材模板', category: 'template' },
    { name: '都市·重生复仇', repo: 'https://github.com/Cola-Pig1121/conovel-templates', description: '都市题材模板', category: 'template' },
    { name: '玄幻·系统流', repo: 'https://github.com/Cola-Pig1121/conovel-templates', description: '玄幻题材模板', category: 'template' },
  ];

  $derived: filteredOfficial = activeCategory === 'all' ? officialTemplates : officialTemplates.filter(t => t.category === activeCategory);

  onMount(async () => {
    if (isTauri()) {
      try { templates = await tauriInvoke('list_templates'); } catch {}
    }
    try { const data = await api.get('/api/books'); books = data.books || []; } catch {}
    loading = false;
  });

  async function handleExport() {
    if (!exportBookId || !exportName.trim()) return;
    try {
      await tauriInvoke('export_template', { book_id: exportBookId, template_name: exportName.trim(), description: exportDesc.trim() });
      toasts.add('导出成功', 'success');
      showExport = false;
      templates = await tauriInvoke('list_templates');
    } catch { toasts.add('导出失败', 'error'); }
  }

  async function handleClone() {
    if (!cloneUrl.trim()) return;
    status = '克隆中...';
    try {
      await tauriInvoke('clone_template', { repo_url: cloneUrl.trim() });
      toasts.add('克隆成功', 'success');
      showClone = false;
      status = '';
      templates = await tauriInvoke('list_templates');
    } catch { toasts.add('克隆失败', 'error'); status = ''; }
  }

  async function handleImport(name) {
    status = '导入中...';
    try {
      const res = await tauriInvoke('import_template', { template_name: name, new_book_id: crypto.randomUUID(), new_book_title: name });
      toasts.add('导入成功', 'success');
      status = '';
    } catch { toasts.add('导入失败', 'error'); status = ''; }
  }

  async function handleDelete(name) {
    if (!confirm(`删除模板 ${name}？`)) return;
    try { await tauriInvoke('delete_template', { template_name: name }); templates = await tauriInvoke('list_templates'); toasts.add('已删除', 'success'); } catch { toasts.add('删除失败', 'error'); }
  }
</script>

<div class="p-8">
  <div class="flex items-center justify-between mb-6">
    <h1 class="font-serif text-xl tracking-tight">模板商店</h1>
    <div class="flex gap-2">
      {#if isTauri()}
        <button onclick={() => showExport = true} class="border border-border px-3 py-1.5 text-xs hover:border-foreground transition-colors">导出模板</button>
        <button onclick={() => showClone = true} class="border border-border px-3 py-1.5 text-xs hover:border-foreground transition-colors">从 GitHub 克隆</button>
      {/if}
    </div>
  </div>

  {#if status}
    <div class="mb-4 p-3 border border-border text-xs text-muted">{status}</div>
  {/if}

  <!-- Category Tabs -->
  <div class="flex gap-1 mb-6 border-b border-border">
    {#each CATEGORIES as cat}
      <button onclick={() => activeCategory = cat.id} class="px-4 py-2 text-xs transition-colors {activeCategory === cat.id ? 'border-b-2 border-foreground' : 'text-muted hover:text-foreground'}">{cat.label}</button>
    {/each}
  </div>

  <!-- Local Templates -->
  {#if isTauri()}
    <section class="mb-8">
      <h3 class="text-[10px] uppercase tracking-widest text-muted mb-3">本地模板</h3>
      {#if loading}
        <p class="text-xs text-muted">加载中...</p>
      {:else if templates.length === 0}
        <p class="text-xs text-muted py-4">暂无本地模板</p>
      {:else}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {#each templates as t}
            <div class="border border-border p-4">
              <p class="text-sm font-medium mb-1">{t.name}</p>
              {#if t.description}<p class="text-xs text-muted mb-3">{t.description}</p>{/if}
              <div class="flex gap-2">
                <button onclick={() => handleImport(t.name)} class="bg-foreground text-background px-3 py-1 text-[10px] border border-foreground hover:bg-transparent hover:text-foreground transition-colors">导入</button>
                <button onclick={() => handleDelete(t.name)} class="text-red-500 hover:text-red-700 text-[10px]">删除</button>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </section>
  {/if}

  <!-- Official Templates -->
  <section>
    <h3 class="text-[10px] uppercase tracking-widest text-muted mb-3">官方模板</h3>
    {#if filteredOfficial.length === 0}
      <p class="text-xs text-muted py-4 text-center">该分类下暂无模板</p>
    {:else}
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {#each filteredOfficial as t}
          <div class="border border-border p-4">
            <p class="text-sm font-medium mb-1">{t.name}</p>
            <p class="text-xs text-muted mb-3">{t.description}</p>
            {#if isTauri()}
              <button onclick={async () => { status = '克隆中...'; try { await tauriInvoke('clone_template', { repo_url: t.repo }); toasts.add('克隆成功', 'success'); templates = await tauriInvoke('list_templates'); } catch { toasts.add('克隆失败', 'error'); } status = ''; }} class="bg-foreground text-background px-3 py-1 text-[10px] border border-foreground hover:bg-transparent hover:text-foreground transition-colors">克隆使用</button>
            {:else}
              <a href={t.repo} target="_blank" class="text-xs text-muted underline hover:text-foreground">查看模板</a>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </section>
</div>

<!-- Export Modal -->
{#if showExport}
  <div class="fixed inset-0 z-[100] flex items-center justify-center" onclick={() => showExport = false}>
    <div class="fixed inset-0 bg-black/30"></div>
    <div class="relative bg-background border border-border w-[28rem] p-6" onclick={(e) => e.stopPropagation()}>
      <h3 class="font-serif text-lg mb-4">导出模板</h3>
      <div class="space-y-4">
        <div><label class="text-xs text-muted block mb-1">选择书籍</label><select bind:value={exportBookId} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground"><option value="">选择...</option>{#each books as b}<option value={b.id}>{b.title}</option>{/each}</select></div>
        <div><label class="text-xs text-muted block mb-1">模板名称 *</label><input type="text" bind:value={exportName} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="My Template" /></div>
        <div><label class="text-xs text-muted block mb-1">描述</label><textarea bind:value={exportDesc} class="w-full border border-border px-3 py-2 text-sm bg-transparent h-16 resize-none focus:outline-none focus:border-foreground"></textarea></div>
      </div>
      <div class="flex justify-end gap-2 mt-6">
        <button onclick={() => showExport = false} class="border border-border px-4 py-2 text-xs hover:border-foreground transition-colors">取消</button>
        <button onclick={handleExport} disabled={!exportBookId || !exportName.trim()} class="bg-foreground text-background px-4 py-2 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors disabled:opacity-40">导出</button>
      </div>
    </div>
  </div>
{/if}

<!-- Clone Modal -->
{#if showClone}
  <div class="fixed inset-0 z-[100] flex items-center justify-center" onclick={() => showClone = false}>
    <div class="fixed inset-0 bg-black/30"></div>
    <div class="relative bg-background border border-border w-[28rem] p-6" onclick={(e) => e.stopPropagation()}>
      <h3 class="font-serif text-lg mb-4">从 GitHub 克隆</h3>
      <div><label class="text-xs text-muted block mb-1">仓库 URL</label><input type="url" bind:value={cloneUrl} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="https://github.com/user/repo" /></div>
      <div class="flex justify-end gap-2 mt-6">
        <button onclick={() => showClone = false} class="border border-border px-4 py-2 text-xs hover:border-foreground transition-colors">取消</button>
        <button onclick={handleClone} disabled={!cloneUrl.trim()} class="bg-foreground text-background px-4 py-2 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors disabled:opacity-40">克隆</button>
      </div>
    </div>
  </div>
{/if}

// packages/studio/src/app/(dashboard)/store/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { isTauri, tauriInvoke, waitForTauri } from '@/lib/tauri';

interface Template {
  name: string;
  description?: string;
  version?: string;
  createdAt?: string;
  category?: string;
}

const CATEGORIES = [
  { id: 'all', label: '全部' },
  { id: 'template', label: '项目模板' },
  { id: 'style', label: '风格包' },
  { id: 'constraint', label: '约束规则' },
  { id: 'reference', label: '参考作品' },
  { id: 'plugin', label: '插件' },
];

export default function StorePage() {
  const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true);
  const [showExportModal, setShowExportModal] = useState(false);
  const [showCloneModal, setShowCloneModal] = useState(false);
  const [exportForm, setExportForm] = useState({ bookId: '', templateName: '', description: '' });
  const [cloneUrl, setCloneUrl] = useState('');
  const [books, setBooks] = useState<any[]>([]);
  const [status, setStatus] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');

  useEffect(() => {
    loadTemplates();
    loadBooks();
  }, []);

  const loadTemplates = async () => {
    setLoading(true);
    try {
      const ready = await waitForTauri(3000);
      if (ready) {
        const result = await tauriInvoke<Template[]>('list_templates');
        setTemplates(result);
      } else {
        setTemplates([]);
      }
    } catch { setTemplates([]); }
    setLoading(false);
  };

  const loadBooks = async () => {
    try {
      const data = await api.get<any>('/api/books');
      setBooks(data.books || []);
    } catch { /* ignore */ }
  };

  const checkTauri = async () => { if (!(await waitForTauri(3000))) { setStatus('此功能仅在 Tauri 桌面端可用'); return false; } return true; };

  const handleExport = async () => {
    if (!checkTauri() || !exportForm.bookId || !exportForm.templateName) return;
    try { await tauriInvoke('export_template', { book_id: exportForm.bookId, template_name: exportForm.templateName, description: exportForm.description }); setStatus('模板已导出'); setShowExportModal(false); loadTemplates(); } catch (e: any) { setStatus(`导出失败: ${e}`); }
  };

  const handleImport = async (templateName: string) => {
    if (!checkTauri()) return;
    const title = prompt('新项目名称：');
    if (!title) return;
    try { const res = await tauriInvoke<any>('import_template', { template_name: templateName, new_book_id: crypto.randomUUID(), new_book_title: title }); setStatus(`模板已导入到 ${res.bookId}`); window.location.href = `/books/${res.bookId}`; } catch (e: any) { setStatus(`导入失败: ${e}`); }
  };

  const handleClone = async () => {
    if (!checkTauri() || !cloneUrl) return;
    try { await tauriInvoke('clone_template', { repo_url: cloneUrl }); setStatus('模板仓库已拉取'); setShowCloneModal(false); loadTemplates(); } catch (e: any) { setStatus(`拉取失败: ${e}`); }
  };

  const handlePush = async (templateName: string) => {
    if (!checkTauri()) return;
    const url = prompt('GitHub 仓库地址：');
    if (!url) return;
    try { await tauriInvoke('push_template', { template_name: templateName, repo_url: url }); setStatus('已推送到 GitHub'); } catch (e: any) { setStatus(`推送失败: ${e}`); }
  };

  // Official templates
  const officialTemplates = [
    { name: '仙侠·废柴逆袭', repo: 'https://github.com/Cola-Pig1121/conovel-templates', description: '仙侠题材模板：废柴逆袭型主角，修仙世界观，门派体系', category: 'template' },
    { name: '都市·重生复仇', repo: 'https://github.com/Cola-Pig1121/conovel-templates', description: '都市题材模板：重生复仇型主角，商战+感情线', category: 'template' },
    { name: '玄幻·系统流', repo: 'https://github.com/Cola-Pig1121/conovel-templates', description: '玄幻题材模板：系统辅助成长，快节奏', category: 'template' },
  ];

  const filteredOfficial = activeCategory === 'all'
    ? officialTemplates
    : officialTemplates.filter(t => t.category === activeCategory);

  return (
    <div>
      <header className="mb-8 px-12 pt-6">
        <h2 className="font-serif text-2xl tracking-tight">模板商店</h2>
        <p className="text-muted text-sm mt-1">导出、导入和共享项目配置模板</p>
      </header>

      <div className="px-12 pb-12">
        {status && (
          <div className="mb-4 p-3 border border-border text-sm">{status}</div>
        )}

        {/* Category Tabs */}
        <div className="flex gap-1 mb-6 border-b border-border">
          {CATEGORIES.map(cat => (
            <button
              key={cat.id}
              onClick={() => setActiveCategory(cat.id)}
              className={`px-4 py-2 text-xs transition-colors ${
                activeCategory === cat.id
                  ? 'border-b-2 border-foreground text-foreground'
                  : 'text-muted hover:text-foreground'
              }`}
            >
              {cat.label}
            </button>
          ))}
        </div>

        {/* Actions */}
        <div className="flex gap-3 mb-8">
          <button onClick={() => setShowExportModal(true)} className="btn-editorial-primary text-xs">导出模板</button>
          <button onClick={() => setShowCloneModal(true)} className="btn-editorial text-xs">从 GitHub 拉取</button>
        </div>

        {/* Local Templates */}
        <section className="mb-12">
          <h3 className="label-editorial text-muted mb-4">我的模板</h3>
          {loading ? (
            <p className="text-muted text-sm">加载中...</p>
          ) : templates.length === 0 ? (
            <div className="card-editorial text-center py-8">
              <p className="text-muted mb-2">暂无本地模板</p>
              <p className="text-xs text-muted">导出项目配置或从 GitHub 拉取模板</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {templates.map((t, i) => (
                <div key={i} className="card-editorial">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="font-serif">{t.name}</p>
                      {t.description && <p className="text-xs text-muted mt-1">{t.description}</p>}
                    </div>
                    {t.version && <span className="text-xs text-muted font-mono">v{t.version}</span>}
                  </div>
                  <div className="flex gap-2 pt-3 border-t border-border">
                    <button onClick={() => handleImport(t.name)} className="btn-editorial text-xs flex-1">使用此模板</button>
                    <button onClick={() => handlePush(t.name)} className="btn-editorial text-xs">推送到 GitHub</button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* Official Templates */}
        <section>
          <h3 className="label-editorial text-muted mb-4">官方模板</h3>
          {filteredOfficial.length === 0 ? (
            <div className="card-editorial text-center py-8">
              <p className="text-muted text-sm">该分类下暂无模板</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredOfficial.map((t, i) => (
              <div key={i} className="card-editorial">
                <p className="font-serif mb-2">{t.name}</p>
                <p className="text-xs text-muted mb-3">{t.description}</p>
                <div className="flex gap-2 pt-3 border-t border-border">
                  <button onClick={async () => {
                    if (!checkTauri()) return;
                    try {
                      await tauriInvoke('clone_template', { repo_url: t.repo, template_name: t.name });
                      setStatus(`已拉取: ${t.name}`);
                      loadTemplates();
                    } catch (e: any) { setStatus(`拉取失败: ${e}`); }
                  }} className="btn-editorial-primary text-xs flex-1">拉取</button>
                </div>
              </div>
            ))}
            </div>
          )}
        </section>
      </div>

      {/* Export Modal */}
      {showExportModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-background border border-border w-[32rem] p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-serif text-lg">导出模板</h3>
              <button onClick={() => setShowExportModal(false)} className="text-muted hover:text-foreground">✕</button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="label-editorial block mb-2">选择项目</label>
                <select value={exportForm.bookId} onChange={e => setExportForm({ ...exportForm, bookId: e.target.value })} className="input-editorial">
                  <option value="">选择项目...</option>
                  {books.map(b => <option key={b.id} value={b.id}>{b.title}</option>)}
                </select>
              </div>
              <div>
                <label className="label-editorial block mb-2">模板名称</label>
                <input type="text" value={exportForm.templateName} onChange={e => setExportForm({ ...exportForm, templateName: e.target.value })} className="input-editorial" placeholder="如：仙侠·废柴逆袭" />
              </div>
              <div>
                <label className="label-editorial block mb-2">描述</label>
                <textarea value={exportForm.description} onChange={e => setExportForm({ ...exportForm, description: e.target.value })} className="input-editorial" rows={2} placeholder="模板描述..." />
              </div>
              <p className="text-xs text-muted">导出内容：风格配置、约束文件、参考小说。不含章节内容。</p>
            </div>
            <div className="flex gap-4 mt-6 pt-4 border-t border-border">
              <button onClick={() => setShowExportModal(false)} className="btn-editorial flex-1">取消</button>
              <button onClick={handleExport} className="btn-editorial-primary flex-1" disabled={!exportForm.bookId || !exportForm.templateName}>导出</button>
            </div>
          </div>
        </div>
      )}

      {/* Clone Modal */}
      {showCloneModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-background border border-border w-[32rem] p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-serif text-lg">从 GitHub 拉取模板</h3>
              <button onClick={() => setShowCloneModal(false)} className="text-muted hover:text-foreground">✕</button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="label-editorial block mb-2">仓库地址</label>
                <input type="url" value={cloneUrl} onChange={e => setCloneUrl(e.target.value)} className="input-editorial" placeholder="https://github.com/user/repo" />
              </div>
              <p className="text-xs text-muted">需要本地安装 Git。仓库应包含 style.json、constraints/ 等配置文件。</p>
            </div>
            <div className="flex gap-4 mt-6 pt-4 border-t border-border">
              <button onClick={() => setShowCloneModal(false)} className="btn-editorial flex-1">取消</button>
              <button onClick={handleClone} className="btn-editorial-primary flex-1" disabled={!cloneUrl}>拉取</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
