// packages/studio/src/lib/components/settings/AgentModelConfig.svelte
<script>
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import { toasts } from '$lib/stores/toast';

  const AGENTS = [
    { role: 'architect', name: 'Architect', nameZh: '故事架构师', category: '核心创作' },
    { role: 'writer', name: 'Writer', nameZh: '写作特工', category: '核心创作' },
    { role: 'character-intelligence', name: 'Character Intelligence', nameZh: '角色智能体', category: '核心创作' },
    { role: 'reviewer', name: 'Reviewer', nameZh: '审阅官', category: '质量控制' },
    { role: 'editor', name: 'Editor', nameZh: '编辑', category: '质量控制' },
    { role: 'de-ai-editor', name: 'De-AI Editor', nameZh: '去AI味编辑', category: '质量控制' },
    { role: 'fact-checker', name: 'Fact Checker', nameZh: '事实核查官', category: '质量控制' },
    { role: 'continuity', name: 'Continuity', nameZh: '连续性检查官', category: '质量控制' },
    { role: 'pacing-controller', name: 'Pacing Controller', nameZh: '节奏控制官', category: '质量控制' },
    { role: 'style-analyzer', name: 'Style Analyzer', nameZh: '风格分析师', category: '辅助' },
    { role: 'observer', name: 'Observer', nameZh: '观察者', category: '辅助' },
    { role: 'character-designer', name: 'Character Designer', nameZh: '角色设计师', category: '辅助' },
    { role: 'foreshadowing', name: 'Foreshadowing', nameZh: '伏笔管理官', category: '辅助' },
    { role: 'radar', name: 'Radar', nameZh: '趋势雷达', category: '辅助' },
    { role: 'reflector', name: 'Reflector', nameZh: '反思官', category: '辅助' },
  ];

  let providers = $state([]);
  let agentConfigs = $state({});
  let loading = $state(true);
  let selectedAgent = $state(null);

  // Tier config
  let tierProvider = $state('');
  let tierStrong = $state('');
  let tierMedium = $state('');
  let tierLight = $state('');

  $effect(() => {
    tierStrong = ''; tierMedium = ''; tierLight = '';
  });

  onMount(async () => {
    try {
      const [pData, aData] = await Promise.all([
        api.get('/api/config?type=providers'),
        api.get('/api/config?type=agents'),
      ]);
      providers = (pData.providers || []).filter(p => p.enabled);
      const configs = aData.agents || [];
      configs.forEach(c => { agentConfigs[c.role] = c; });
    } catch {}
    loading = false;
  });

  function getProviderModels(providerName) {
    const p = providers.find(p => p.name === providerName);
    return p?.models || [];
  }

  async function saveConfig(role) {
    const config = agentConfigs[role];
    if (!config) return;
    try {
      await api.put('/api/config', { type: 'single-agent', role, ...config });
      toasts.add(`${AGENTS.find(a => a.role === role)?.nameZh || role} 已保存`, 'success');
    } catch { toasts.add('保存失败', 'error'); }
  }

  async function applyTierConfig() {
    if (!tierProvider || !tierStrong || !tierMedium || !tierLight) return;
    const models = getProviderModels(tierProvider);
    const strong = models.find(m => m.id === tierStrong);
    const medium = models.find(m => m.id === tierMedium);
    const light = models.find(m => m.id === tierLight);

    const tierMap = {
      'architect': strong, 'character-intelligence': strong,
      'writer': medium, 'editor': medium, 'reviewer': medium, 'de-ai-editor': medium,
      'fact-checker': light, 'continuity': light, 'foreshadowing': light, 'observer': light, 'radar': light,
      'pacing-controller': medium, 'style-analyzer': medium, 'character-designer': medium,
      'reflector': medium,
    };

    for (const agent of AGENTS) {
      const model = tierMap[agent.role] || medium;
      if (model) {
        agentConfigs[agent.role] = {
          ...agentConfigs[agent.role],
          role: agent.role, provider: tierProvider, modelId: model.id,
          enabled: true, temperature: 0.7, maxTokens: 4096,
        };
      }
    }

    try {
      await api.put('/api/config', { type: 'agents', agents: Object.values(agentConfigs) });
      toasts.add('批量分配完成', 'success');
    } catch { toasts.add('分配失败', 'error'); }
  }
</script>

{#if loading}
  <p class="text-sm text-muted">加载中...</p>
{:else}
  <div class="flex gap-8">
    <!-- Left: Agent list -->
    <div class="w-64 flex-shrink-0 space-y-4">
      {#each ['核心创作', '质量控制', '辅助'] as category}
        <div>
          <p class="text-[10px] uppercase tracking-widest text-muted mb-2">{category}</p>
          <div class="space-y-0.5">
            {#each AGENTS.filter(a => a.category === category) as agent}
              <button onclick={() => selectedAgent = agent.role} class="w-full text-left px-3 py-2 text-xs transition-colors flex items-center justify-between {selectedAgent === agent.role ? 'bg-foreground/10 text-foreground' : 'text-muted hover:text-foreground hover:bg-foreground/5'}">
                <span>{agent.nameZh}</span>
                {#if agentConfigs[agent.role]?.modelId}
                  <span class="w-2 h-2 rounded-full bg-green-500"></span>
                {:else}
                  <span class="w-2 h-2 rounded-full bg-muted/30"></span>
                {/if}
              </button>
            {/each}
          </div>
        </div>
      {/each}
    </div>

    <!-- Right: Config -->
    <div class="flex-1 min-w-0">
      <!-- Tier config -->
      <div class="border border-border p-4 mb-6">
        <p class="text-[10px] uppercase tracking-widest text-muted mb-3">快速配置 — 按模型能力分层分配</p>
        <div class="grid grid-cols-4 gap-3">
          <div>
            <label class="text-xs text-muted block mb-1">服务商</label>
            <select bind:value={tierProvider} class="w-full border border-border px-2 py-1.5 text-xs bg-transparent focus:outline-none focus:border-foreground">
              <option value="">选择...</option>
              {#each providers as p}<option value={p.name}>{p.name}</option>{/each}
            </select>
          </div>
          <div>
            <label class="text-xs text-muted block mb-1">强模型</label>
            <select bind:value={tierStrong} class="w-full border border-border px-2 py-1.5 text-xs bg-transparent focus:outline-none focus:border-foreground">
              <option value="">选择...</option>
              {#each getProviderModels(tierProvider) as m}<option value={m.id}>{m.id}</option>{/each}
            </select>
          </div>
          <div>
            <label class="text-xs text-muted block mb-1">中模型</label>
            <select bind:value={tierMedium} class="w-full border border-border px-2 py-1.5 text-xs bg-transparent focus:outline-none focus:border-foreground">
              <option value="">选择...</option>
              {#each getProviderModels(tierProvider) as m}<option value={m.id}>{m.id}</option>{/each}
            </select>
          </div>
          <div>
            <label class="text-xs text-muted block mb-1">轻模型</label>
            <select bind:value={tierLight} class="w-full border border-border px-2 py-1.5 text-xs bg-transparent focus:outline-none focus:border-foreground">
              <option value="">选择...</option>
              {#each getProviderModels(tierProvider) as m}<option value={m.id}>{m.id}</option>{/each}
            </select>
          </div>
        </div>
        <button onclick={applyTierConfig} disabled={!tierProvider || !tierStrong || !tierMedium || !tierLight} class="mt-3 bg-foreground text-background px-4 py-1.5 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors disabled:opacity-40">应用分配</button>
      </div>

      <!-- Per-agent config -->
      {#if selectedAgent}
        {@const agent = AGENTS.find(a => a.role === selectedAgent)}
        {@const config = agentConfigs[selectedAgent] || {}}
        <div class="space-y-4">
          <p class="text-[10px] uppercase tracking-widest text-muted">{agent?.nameZh} ({agent?.name})</p>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="text-xs text-muted block mb-1">服务商</label>
              <select bind:value={config.provider} onchange={(e) => { config.provider = e.target.value; config.modelId = ''; agentConfigs[selectedAgent] = { ...config }; }} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground">
                <option value="">选择...</option>
                {#each providers as p}<option value={p.name}>{p.name}</option>{/each}
              </select>
            </div>
            <div>
              <label class="text-xs text-muted block mb-1">模型</label>
              <select bind:value={config.modelId} onchange={(e) => { config.modelId = e.target.value; agentConfigs[selectedAgent] = { ...config }; }} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground">
                <option value="">选择...</option>
                {#each getProviderModels(config.provider) as m}<option value={m.id}>{m.id}</option>{/each}
              </select>
            </div>
            <div>
              <label class="text-xs text-muted block mb-1">Temperature</label>
              <input type="number" step="0.1" min="0" max="2" bind:value={config.temperature} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" />
            </div>
            <div>
              <label class="text-xs text-muted block mb-1">Max Tokens</label>
              <input type="number" step="256" bind:value={config.maxTokens} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" />
            </div>
          </div>
          <button onclick={() => saveConfig(selectedAgent)} class="bg-foreground text-background px-4 py-2 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors">保存配置</button>
        </div>
      {:else}
        <div class="text-center py-16 text-muted text-sm">选择左侧 Agent 进行配置</div>
      {/if}
    </div>
  </div>
{/if}

// packages/studio/src/components/settings/AgentModelConfig.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';

// Agent Model Config - Per-Agent模型配置组件
// 配置持久化到 ~/.config/conovel/agents.json

interface AgentConfig {
  role: string;
  name: string;
  nameZh: string;
  provider: string;
  modelId: string;
  temperature: number;
  maxTokens: number;
  contextWindow: number;
}

interface Provider {
  id: string;
  name: string;
  models: { id: string }[];
  enabled: boolean;
}

const AGENT_ROLES: Array<{ role: string; name: string; nameZh: string; category: string }> = [
  { role: 'architect', name: 'Architect', nameZh: '故事架构师', category: '核心创作' },
  { role: 'writer', name: 'Writer', nameZh: '写作特工', category: '核心创作' },
  { role: 'character-intelligence', name: 'Character Intelligence', nameZh: '角色智能体', category: '核心创作' },
  { role: 'reviewer', name: 'Reviewer', nameZh: '审阅官', category: '质量控制' },
  { role: 'editor', name: 'Editor', nameZh: '编辑', category: '质量控制' },
  { role: 'de-ai-editor', name: 'De-AI Editor', nameZh: '去AI味编辑', category: '质量控制' },
  { role: 'fact-checker', name: 'Fact Checker', nameZh: '事实核查官', category: '质量控制' },
  { role: 'continuity', name: 'Continuity', nameZh: '连续性检查官', category: '质量控制' },
  { role: 'pacing-controller', name: 'Pacing Controller', nameZh: '节奏控制官', category: '质量控制' },
  { role: 'style-analyzer', name: 'Style Analyzer', nameZh: '风格分析师', category: '辅助' },
  { role: 'observer', name: 'Observer', nameZh: '观察者', category: '辅助' },
  { role: 'character-designer', name: 'Character Designer', nameZh: '角色设计师', category: '辅助' },
  { role: 'foreshadowing', name: 'Foreshadowing', nameZh: '伏笔管理官', category: '辅助' },
  { role: 'radar', name: 'Radar', nameZh: '趋势雷达', category: '辅助' },
  { role: 'reflector', name: 'Reflector', nameZh: '反思官', category: '辅助' },
];

export function AgentModelConfig() {
  const [configs, setConfigs] = useState<AgentConfig[]>([]);
  const [providers, setProviders] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedAgent, setSelectedAgent] = useState<string>('architect');

  // Load from API on mount
  useEffect(() => {
    Promise.all([
      fetch('/api/config?type=agents').then(r => r.json()),
      fetch('/api/config?type=providers').then(r => r.json()),
    ]).then(([agentsData, providersData]) => {
      setConfigs(agentsData.agents || []);
      setProviders(providersData.providers || []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  // Save single agent config
  const saveAgentConfig = useCallback(async (role: string, updates: Partial<AgentConfig>) => {
    setConfigs(prev => prev.map(c => c.role === role ? { ...c, ...updates } : c));
    await fetch('/api/config', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'single-agent', role, updates }),
    });
  }, []);

  // Batch save all agents
  const saveAllConfigs = useCallback(async (newConfigs: AgentConfig[]) => {
    setConfigs(newConfigs);
    await fetch('/api/config', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'agents', agents: newConfigs }),
    });
  }, []);

  const selectedConfig = configs.find(c => c.role === selectedAgent);

  // Get models from providers for a specific provider id
  const getModelsForProvider = (providerId: string): string[] => {
    const provider = providers.find(p => p.id === providerId || p.name === providerId);
    return provider?.models.map(m => m.id) || [];
  };

  if (loading) return <div className="text-muted text-sm">加载配置中...</div>;

  const categories = [...new Set(AGENT_ROLES.map(a => a.category))];

  return (
    <div className="flex gap-8">
      {/* Agent List */}
      <div className="w-72 flex-shrink-0">
        <div className="mb-4">
          <h3 className="label-editorial text-muted">Agent 列表</h3>
        </div>
        <div className="space-y-6">
          {categories.map(category => (
            <div key={category}>
              <p className="text-xs text-muted mb-2 font-mono tracking-wider uppercase">{category}</p>
              <div className="space-y-1">
                {AGENT_ROLES.filter(a => a.category === category).map(agent => (
                  <button
                    key={agent.role}
                    onClick={() => setSelectedAgent(agent.role)}
                    className={`w-full text-left px-4 py-2 text-sm transition-colors ${
                      selectedAgent === agent.role ? 'bg-foreground text-background' : 'hover:bg-foreground/5'
                    }`}
                  >
                    <span className="font-sans">{agent.nameZh}</span>
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Configuration Panel */}
      {selectedConfig ? (
        <div className="flex-1">
          <div className="card-editorial">
            <div className="mb-6">
              <h3 className="font-serif text-lg">{selectedConfig.nameZh}</h3>
              <p className="font-mono text-sm text-muted mt-1">{selectedConfig.name}</p>
            </div>
            <div className="space-y-6">
              {/* Model Provider */}
              <div>
                <label className="label-editorial block mb-2">模型供应商</label>
                <select
                  value={selectedConfig.provider}
                  onChange={(e) => {
                    const newProvider = e.target.value;
                    const models = getModelsForProvider(newProvider);
                    saveAgentConfig(selectedConfig.role, {
                      provider: newProvider,
                      modelId: models[0] || '',
                    });
                  }}
                  className="input-editorial"
                >
                  {providers.filter(p => p.enabled).map(p => (
                    <option key={p.id} value={p.name}>{p.name}</option>
                  ))}
                </select>
              </div>

              {/* Model Selection */}
              <div>
                <label className="label-editorial block mb-2">模型选择</label>
                <select
                  value={selectedConfig.modelId}
                  onChange={(e) => saveAgentConfig(selectedConfig.role, { modelId: e.target.value })}
                  className="input-editorial"
                >
                  {getModelsForProvider(selectedConfig.provider).map(m => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </select>
              </div>

              {/* Parameters */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label-editorial block mb-2">Temperature</label>
                  <input type="number" min="0" max="2" step="0.1" value={selectedConfig.temperature}
                    onChange={(e) => saveAgentConfig(selectedConfig.role, { temperature: parseFloat(e.target.value) })}
                    className="input-editorial" />
                  <p className="text-xs text-muted mt-1">0 = 精确，1 = 创造性</p>
                </div>
                <div>
                  <label className="label-editorial block mb-2">Max Tokens</label>
                  <input type="number" min="256" step="256" value={selectedConfig.maxTokens}
                    onChange={(e) => saveAgentConfig(selectedConfig.role, { maxTokens: parseInt(e.target.value) })}
                    className="input-editorial" />
                </div>
              </div>

              {/* Context Window */}
              <div>
                <label className="label-editorial block mb-2">上下文窗口</label>
                <input type="number" min="4096" step="1000" value={selectedConfig.contextWindow}
                  onChange={(e) => saveAgentConfig(selectedConfig.role, { contextWindow: parseInt(e.target.value) })}
                  className="input-editorial" />
                <p className="text-xs text-muted mt-1">模型支持的最大上下文长度</p>
              </div>
            </div>
          </div>

          {/* Quick Actions */}
          <div className="mt-6 card-editorial">
            <h4 className="font-serif text-sm mb-4">快速配置</h4>
            <p className="text-xs text-muted mb-4">
              按角色复杂度选择模型，平衡质量和成本。选择供应商后，手动指定三个等级的模型。
            </p>

            <TierConfig providers={providers} configs={configs} onSave={saveAllConfigs} />

            <p className="text-xs text-muted mt-3 font-mono">
              配置目录: ~/.config/conovel/
            </p>
          </div>
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center text-muted text-sm">
          选择左侧Agent进行配置
        </div>
      )}
    </div>
  );
}

// ===== Tier Config Component =====

const DEEP_REASONING_ROLES = ['architect', 'character-intelligence'];
const LIGHTWEIGHT_ROLES = ['fact-checker', 'continuity', 'foreshadowing', 'observer', 'radar'];

function TierConfig({
  providers,
  configs,
  onSave,
}: {
  providers: { name: string; enabled: boolean; models: { id: string }[] }[];
  configs: AgentConfig[];
  onSave: (configs: AgentConfig[]) => void;
}) {
  const enabled = providers.filter(p => p.enabled);
  const allModels = enabled.flatMap(p => p.models.map(m => ({ provider: p.name, modelId: m.id, label: `${p.name} / ${m.id}` })));

  const [provider, setProvider] = useState(enabled[0]?.name || '');
  const [strongModel, setStrongModel] = useState('');
  const [mediumModel, setMediumModel] = useState('');
  const [lightModel, setLightModel] = useState('');

  // Update provider options when providers change
  const providerModels = allModels.filter(m => m.provider === provider);

  const handleApply = () => {
    onSave(configs.map(c => {
      const needsDeep = DEEP_REASONING_ROLES.includes(c.role);
      const isLight = LIGHTWEIGHT_ROLES.includes(c.role);
      let modelId = mediumModel;
      if (needsDeep) modelId = strongModel;
      if (isLight) modelId = lightModel;
      return { ...c, provider, modelId };
    }));
  };

  return (
    <div className="space-y-4">
      <div>
        <label className="text-sm text-muted block mb-1">供应商</label>
        <select value={provider} onChange={e => { setProvider(e.target.value); setStrongModel(''); setMediumModel(''); setLightModel(''); }} className="input-editorial">
          {enabled.map(p => <option key={p.name} value={p.name}>{p.name}</option>)}
        </select>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <div>
          <label className="text-sm text-muted block mb-1">强模型（深度推理）</label>
          <select value={strongModel} onChange={e => setStrongModel(e.target.value)} className="input-editorial text-xs">
            <option value="">未选择</option>
            {providerModels.map(m => <option key={m.modelId} value={m.modelId}>{m.modelId}</option>)}
          </select>
          <p className="text-xs text-muted mt-1">架构师、角色智能体</p>
        </div>
        <div>
          <label className="text-sm text-muted block mb-1">中等模型（创作审阅）</label>
          <select value={mediumModel} onChange={e => setMediumModel(e.target.value)} className="input-editorial text-xs">
            <option value="">未选择</option>
            {providerModels.map(m => <option key={m.modelId} value={m.modelId}>{m.modelId}</option>)}
          </select>
          <p className="text-xs text-muted mt-1">写作、编辑、审阅官等</p>
        </div>
        <div>
          <label className="text-sm text-muted block mb-1">轻量模型（简单检查）</label>
          <select value={lightModel} onChange={e => setLightModel(e.target.value)} className="input-editorial text-xs">
            <option value="">未选择</option>
            {providerModels.map(m => <option key={m.modelId} value={m.modelId}>{m.modelId}</option>)}
          </select>
          <p className="text-xs text-muted mt-1">事实核查、连续性等</p>
        </div>
      </div>

      <button
        onClick={handleApply}
        disabled={!provider || !strongModel || !mediumModel || !lightModel}
        className="btn-editorial-primary text-xs"
      >
        应用分配
      </button>
    </div>
  );
}
