// packages/studio/src/lib/components/settings/ProviderManager.svelte
<script>
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import { toasts } from '$lib/stores/toast';

  let providers = $state([]);
  let loading = $state(true);
  let editingProvider = $state(null);
  let showAddModal = $state(false);
  let scanning = $state(false);

  let newName = $state('');
  let newBaseUrl = $state('https://api.openai.com/v1');
  let newApiKey = $state('');
  let newApiFormat = $state('openai');

  const API_FORMATS = [
    { value: 'openai', label: 'OpenAI Compatible (/chat/completions)' },
    { value: 'anthropic', label: 'Anthropic (/v1/messages)' },
  ];

  onMount(loadProviders);

  async function loadProviders() {
    try { const data = await api.get('/api/config?type=providers'); providers = data.providers || []; } catch {}
    loading = false;
  }

  async function saveAll() {
    try { await api.put('/api/config', { type: 'providers', providers }); toasts.add('已保存', 'success'); } catch { toasts.add('保存失败', 'error'); }
  }

  function updateEditing(field, value) {
    if (!editingProvider) return;
    editingProvider[field] = value;
    const idx = providers.findIndex(p => p.id === editingProvider.id);
    if (idx >= 0) { providers[idx] = { ...providers[idx], [field]: value }; providers = [...providers]; }
  }

  async function addProvider() {
    if (!newName.trim() || !newApiKey.trim()) return;
    const p = { id: crypto.randomUUID(), name: newName.trim(), baseUrl: newBaseUrl.trim(), apiFormat: newApiFormat, apiKey: newApiKey.trim(), models: [], enabled: true };
    providers = [...providers, p];
    await saveAll();
    showAddModal = false;
    newName = ''; newApiKey = ''; newBaseUrl = 'https://api.openai.com/v1';
    editingProvider = p;
  }

  async function deleteProvider(id) {
    providers = providers.filter(p => p.id !== id);
    if (editingProvider?.id === id) editingProvider = null;
    await saveAll();
  }

  async function toggleProvider(id) {
    providers = providers.map(p => p.id === id ? { ...p, enabled: !p.enabled } : p);
    if (editingProvider?.id === id) editingProvider = providers.find(p => p.id === id);
    await saveAll();
  }

  async function scanModels() {
    if (!editingProvider?.baseUrl || !editingProvider?.apiKey) { toasts.add('请填写 Base URL 和 API Key', 'error'); return; }
    scanning = true;
    try {
      const data = await api.post('/api/models/discover', { baseUrl: editingProvider.baseUrl, apiKey: editingProvider.apiKey, apiFormat: editingProvider.apiFormat });
      if (data.success && data.models) {
        const idx = providers.findIndex(p => p.id === editingProvider.id);
        if (idx >= 0) { providers[idx] = { ...providers[idx], models: data.models }; providers = [...providers]; editingProvider = providers[idx]; }
        await saveAll();
        toasts.add(`发现 ${data.models.length} 个模型`, 'success');
      } else { toasts.add(data.error || '扫描失败', 'error'); }
    } catch (e) { toasts.add('扫描失败', 'error'); }
    scanning = false;
  }
</script>

<div class="flex gap-8">
  <div class="w-64 flex-shrink-0">
    <div class="flex items-center justify-between mb-4">
      <p class="text-[10px] uppercase tracking-widest text-muted">服务商</p>
      <button onclick={() => showAddModal = true} class="text-xs text-muted hover:text-foreground transition-colors">+ 添加</button>
    </div>
    {#if loading}
      <p class="text-xs text-muted">加载中...</p>
    {:else if providers.length === 0}
      <p class="text-xs text-muted">暂无服务商</p>
    {:else}
      <div class="space-y-0.5">
        {#each providers as p}
          <button onclick={() => editingProvider = p} class="w-full text-left px-3 py-2 text-xs transition-colors flex items-center justify-between {editingProvider?.id === p.id ? 'bg-foreground/10 text-foreground' : 'text-muted hover:text-foreground hover:bg-foreground/5'}">
            <span class="truncate">{p.name}</span>
            <span class="w-2 h-2 rounded-full {p.enabled ? 'bg-green-500' : 'bg-muted/30'} flex-shrink-0"></span>
          </button>
        {/each}
      </div>
    {/if}
  </div>

  <div class="flex-1 min-w-0">
    {#if editingProvider}
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <p class="text-[10px] uppercase tracking-widest text-muted">编辑服务商</p>
          <div class="flex gap-2">
            <button onclick={() => toggleProvider(editingProvider.id)} class="border border-border px-3 py-1.5 text-xs hover:border-foreground transition-colors">{editingProvider.enabled ? '禁用' : '启用'}</button>
            <button onclick={() => deleteProvider(editingProvider.id)} class="border border-red-300 text-red-600 px-3 py-1.5 text-xs hover:bg-red-50 transition-colors">删除</button>
          </div>
        </div>
        <div><label class="text-xs text-muted block mb-1">名称</label><input type="text" value={editingProvider.name} oninput={(e) => updateEditing('name', e.target.value)} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" /></div>
        <div><label class="text-xs text-muted block mb-1">Base URL</label><input type="url" value={editingProvider.baseUrl} oninput={(e) => updateEditing('baseUrl', e.target.value)} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="https://api.openai.com/v1" /></div>
        <div><label class="text-xs text-muted block mb-1">API Key</label><input type="password" value={editingProvider.apiKey} oninput={(e) => updateEditing('apiKey', e.target.value)} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="sk-..." /></div>
        <div>
          <label class="text-xs text-muted block mb-1">API 格式</label>
          <select value={editingProvider.apiFormat} onchange={(e) => updateEditing('apiFormat', e.target.value)} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground">
            {#each API_FORMATS as f}<option value={f.value}>{f.label}</option>{/each}
          </select>
        </div>
        <div class="flex gap-2">
          <button onclick={saveAll} class="bg-foreground text-background px-4 py-2 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors">保存配置</button>
          <button onclick={scanModels} disabled={scanning} class="border border-border px-4 py-2 text-xs hover:border-foreground transition-colors disabled:opacity-50">{scanning ? '扫描中...' : '扫描模型'}</button>
        </div>
        {#if editingProvider.models.length > 0}
          <div class="mt-4">
            <p class="text-[10px] uppercase tracking-widest text-muted mb-2">已发现模型 ({editingProvider.models.length})</p>
            <div class="border border-border divide-y divide-border max-h-64 overflow-y-auto">
              {#each editingProvider.models as model}
                <div class="px-3 py-2 text-xs font-mono">{model.id}</div>
              {/each}
            </div>
          </div>
        {/if}
      </div>
    {:else}
      <div class="text-center py-16 text-muted text-sm">选择左侧服务商进行编辑</div>
    {/if}
  </div>
</div>

{#if showAddModal}
  <div class="fixed inset-0 z-[100] flex items-center justify-center" onclick={() => showAddModal = false} onkeydown={(e) => e.key === 'Escape' && (showAddModal = false)} role="dialog" aria-modal="true">
    <div class="fixed inset-0 bg-black/30"></div>
    <div class="relative bg-background border border-border w-[28rem] p-6" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()}>
      <h3 class="font-serif text-lg mb-4">添加服务商</h3>
      <div class="space-y-4">
        <div><label class="text-xs text-muted block mb-1" for="pn">名称 *</label><input id="pn" type="text" bind:value={newName} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="如：OpenAI" /></div>
        <div><label class="text-xs text-muted block mb-1" for="purl">Base URL</label><input id="purl" type="url" bind:value={newBaseUrl} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="https://api.openai.com/v1" /></div>
        <div><label class="text-xs text-muted block mb-1" for="pkey">API Key *</label><input id="pkey" type="password" bind:value={newApiKey} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" placeholder="sk-..." /></div>
        <div><label class="text-xs text-muted block mb-1" for="pfmt">API 格式</label><select id="pfmt" bind:value={newApiFormat} class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground">{#each API_FORMATS as f}<option value={f.value}>{f.label}</option>{/each}</select></div>
      </div>
      <div class="flex justify-end gap-2 mt-6">
        <button onclick={() => showAddModal = false} class="border border-border px-4 py-2 text-xs hover:border-foreground transition-colors">取消</button>
        <button onclick={addProvider} disabled={!newName.trim() || !newApiKey.trim()} class="bg-foreground text-background px-4 py-2 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors disabled:opacity-40">添加</button>
      </div>
    </div>
  </div>
{/if}

// packages/studio/src/components/settings/ProviderManager.tsx
'use client';

import { api } from '@/lib/api';

import { useState, useEffect, useCallback } from 'react';

// Provider Manager - 模型供应商管理组件
// 配置持久化到 ~/.config/conovel/providers.json

interface Provider {
  id: string;
  name: string;
  baseUrl: string;
  apiFormat: 'openai' | 'anthropic';
  apiKey: string;
  models: ModelEntry[];
  status: 'connected' | 'disconnected' | 'error';
  enabled: boolean;
}

interface ModelEntry {
  id: string;
  contextWindow: number;
  supportsReasoning?: boolean;
  reasoningLevels?: string[];
}

const EMPTY_PROVIDER: Provider = {
  id: '',
  name: '',
  baseUrl: '',
  apiFormat: 'openai',
  apiKey: '',
  models: [],
  status: 'disconnected',
  enabled: true,
};

export function ProviderManager() {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(true);
  const [editingProvider, setEditingProvider] = useState<Provider | null>(null);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showAddModelModal, setShowAddModelModal] = useState(false);
  const [newModelId, setNewModelId] = useState('');
  const [newModelContext, setNewModelContext] = useState(200000);
  const [scanning, setScanning] = useState(false);
  const [editingModelId, setEditingModelId] = useState<string | null>(null);
  const [editingModelData, setEditingModelData] = useState<{ id: string; contextWindow: number }>({ id: '', contextWindow: 200000 });

  // Load from API on mount
  useEffect(() => {
    api.get('/api/config?type=providers')
      .then(data => {
        setProviders(data.providers || []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  // Save to API
  const saveProviders = useCallback(async (updated: Provider[]) => {
    setProviders(updated);
    await api.put('/api/config', { type: 'providers', providers: updated });
  }, []);

  // When editing provider changes, keep editing reference in sync
  useEffect(() => {
    if (editingProvider) {
      const fresh = providers.find(p => p.id === editingProvider.id);
      if (fresh) setEditingProvider(fresh);
    }
  }, [providers]);

  const handleAddProvider = async (provider: Omit<Provider, 'id' | 'status'>) => {
    const newProvider: Provider = {
      ...provider,
      id: provider.name.toLowerCase().replace(/\s+/g, '-') + '-' + Date.now(),
      status: 'disconnected',
    };
    const updated = [...providers, newProvider];
    await saveProviders(updated);
    setEditingProvider(newProvider);
    setShowAddModal(false);
  };

  const handleDeleteProvider = async (id: string) => {
    const updated = providers.filter(p => p.id !== id);
    await saveProviders(updated);
    if (editingProvider?.id === id) setEditingProvider(null);
  };

  const handleToggleProvider = async (id: string) => {
    const updated = providers.map(p => p.id === id ? { ...p, enabled: !p.enabled } : p);
    await saveProviders(updated);
    if (editingProvider?.id === id) {
      const fresh = updated.find(p => p.id === id);
      if (fresh) setEditingProvider(fresh);
    }
  };

  const handleSaveEditing = async () => {
    if (!editingProvider) return;
    const updated = providers.map(p => p.id === editingProvider.id ? editingProvider : p);
    await saveProviders(updated);
  };

  const handleAddModel = async () => {
    if (!editingProvider || !newModelId) return;
    const model: ModelEntry = { id: newModelId, contextWindow: newModelContext };
    const updatedProvider = {
      ...editingProvider,
      models: [...editingProvider.models, model],
    };
    const updated = providers.map(p => p.id === editingProvider.id ? updatedProvider : p);
    await saveProviders(updated);
    setEditingProvider(updatedProvider);
    setShowAddModelModal(false);
    setNewModelId('');
    setNewModelContext(200000);
  };

  const handleScanModels = async () => {
    if (!editingProvider) return;
    setScanning(true);
    try {
      const data = await api.post<any>('/api/models/discover', {
          baseUrl: editingProvider.baseUrl,
          apiKey: editingProvider.apiKey,
          apiFormat: editingProvider.apiFormat,
        });
      if (data.success && data.models?.length > 0) {
        // Merge discovered models with existing, preserving manual additions
        const existingIds = new Set(editingProvider.models.map(m => m.id));
        const newModels = data.models
          .filter((m: any) => !existingIds.has(m.id))
          .map((m: any) => ({
            id: m.id,
            contextWindow: m.contextWindow || 200000,
            supportsReasoning: m.supportsReasoning || false,
            reasoningLevels: m.reasoningLevels || [],
          }));
        const merged = [...editingProvider.models, ...newModels];
        const updatedProvider = { ...editingProvider, models: merged };
        const updated = providers.map(p => p.id === editingProvider.id ? updatedProvider : p);
        await saveProviders(updated);
        setEditingProvider(updatedProvider);
      }
    } catch (e) {
      console.error('Scan failed:', e);
    }
    setScanning(false);
  };

  const handleSaveModelEdit = async () => {
    if (!editingProvider || !editingModelId) return;
    const updated = providers.map(p => {
      if (p.id === editingProvider.id) {
        return {
          ...p,
          models: p.models.map(m =>
            m.id === editingModelId
              ? { ...m, id: editingModelData.id, contextWindow: editingModelData.contextWindow }
              : m
          ),
        };
      }
      return p;
    });
    await saveProviders(updated);
    const fresh = updated.find(p => p.id === editingProvider.id);
    if (fresh) setEditingProvider(fresh);
    setEditingModelId(null);
  };

  const handleDeleteModel = async (providerId: string, modelId: string) => {
    const updated = providers.map(p => {
      if (p.id === providerId) {
        return { ...p, models: p.models.filter(m => m.id !== modelId) };
      }
      return p;
    });
    await saveProviders(updated);
    // Sync editing state
    const fresh = updated.find(p => p.id === providerId);
    if (fresh) setEditingProvider(fresh);
  };

  if (loading) return <div className="text-muted text-sm">加载配置中...</div>;

  return (
    <div className="flex gap-8">
      {/* Provider List */}
      <div className="w-64 flex-shrink-0">
        <div className="mb-4">
          <h3 className="label-editorial text-muted">供应商列表</h3>
        </div>
        <div className="space-y-2">
          {providers.map((provider) => (
            <div
              key={provider.id}
              className={`w-full text-left px-4 py-3 text-sm transition-colors border ${
                editingProvider?.id === provider.id
                  ? 'border-foreground bg-foreground/5'
                  : 'border-border hover:border-foreground/50'
              }`}
            >
              <div className="flex items-center justify-between">
                <button
                  onClick={() => setEditingProvider(provider)}
                  className="flex-1 text-left"
                >
                  <span className={`font-sans ${!provider.enabled ? 'text-muted line-through' : ''}`}>{provider.name}</span>
                </button>
                <button
                  onClick={() => handleToggleProvider(provider.id)}
                  className={`ml-2 w-9 h-5 rounded-full transition-colors relative ${
                    provider.enabled ? 'bg-foreground' : 'bg-muted/30'
                  }`}
                  title={provider.enabled ? '点击禁用' : '点击启用'}
                >
                  <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-background transition-transform ${
                    provider.enabled ? 'translate-x-4' : 'translate-x-0.5'
                  }`} />
                </button>
              </div>
            </div>
          ))}
        </div>
        <button onClick={() => setShowAddModal(true)} className="w-full mt-4 px-4 py-3 text-sm border border-border hover:border-foreground transition-colors">
          + 添加供应商
        </button>
        <p className="text-xs text-muted mt-3 font-mono">
          配置目录: ~/.config/conovel/
        </p>
      </div>

      {/* Provider Configuration Panel */}
      {editingProvider ? (
        <div className="flex-1">
          <div className="card-editorial">
            <h3 className="font-serif text-lg mb-6">供应商配置</h3>
            <div className="space-y-6">
              <div>
                <label className="label-editorial block mb-2">名称</label>
                <input type="text" value={editingProvider.name} onChange={(e) => setEditingProvider({ ...editingProvider, name: e.target.value })} className="input-editorial" placeholder="如：智谱 GLM" />
              </div>
              <div>
                <label className="label-editorial block mb-2">Base URL</label>
                <input type="url" value={editingProvider.baseUrl} onChange={(e) => setEditingProvider({ ...editingProvider, baseUrl: e.target.value })} className="input-editorial" placeholder="https://api.example.com/v1" />
              </div>
              <div>
                <label className="label-editorial block mb-2">API Key</label>
                <input type="password" value={editingProvider.apiKey} onChange={(e) => setEditingProvider({ ...editingProvider, apiKey: e.target.value })} className="input-editorial" placeholder="输入 API Key" />
              </div>
              <div>
                <label className="label-editorial block mb-2">API 格式</label>
                <select value={editingProvider.apiFormat} onChange={(e) => setEditingProvider({ ...editingProvider, apiFormat: e.target.value as Provider['apiFormat'] })} className="input-editorial">
                  <option value="openai">OpenAI Compatible (/chat/completions)</option>
                  <option value="anthropic">Anthropic (/v1/messages)</option>
                </select>
              </div>

              {/* Model List */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="label-editorial">模型列表</label>
                  <button
                    onClick={handleScanModels}
                    disabled={scanning}
                    className="btn-editorial text-xs"
                  >
                    {scanning ? '扫描中...' : '扫描模型'}
                  </button>
                </div>
                <div className="space-y-2 mb-3">
                  {editingProvider.models.map((model) => (
                    <div key={model.id} className="border border-border">
                      {editingModelId === model.id ? (
                        /* Edit mode */
                        <div className="p-3 space-y-2">
                          <div>
                            <label className="text-xs text-muted">模型 ID</label>
                            <input
                              type="text"
                              value={editingModelData.id}
                              onChange={(e) => setEditingModelData({ ...editingModelData, id: e.target.value })}
                              className="input-editorial text-sm mt-1"
                            />
                          </div>
                          <div>
                            <label className="text-xs text-muted">上下文窗口</label>
                            <input
                              type="number"
                              value={editingModelData.contextWindow}
                              onChange={(e) => setEditingModelData({ ...editingModelData, contextWindow: Number(e.target.value) })}
                              className="input-editorial text-sm mt-1"
                            />
                          </div>
                          <div className="flex gap-2">
                            <button onClick={() => setEditingModelId(null)} className="btn-editorial text-xs flex-1">取消</button>
                            <button onClick={handleSaveModelEdit} className="btn-editorial-primary text-xs flex-1">保存</button>
                          </div>
                        </div>
                      ) : (
                        /* Display mode */
                        <div className="flex items-center justify-between py-2 px-3">
                          <div className="flex-1">
                            <div className="flex items-center gap-2">
                              <p className="font-mono text-sm">{model.id}</p>
                              {model.supportsReasoning && (
                                <span className="px-1.5 py-0.5 text-[10px] bg-foreground/10 text-foreground font-mono">
                                  thinking
                                </span>
                              )}
                            </div>
                            <div className="flex items-center gap-3 mt-0.5">
                              {model.contextWindow > 0 && (
                                <p className="text-xs text-muted">上下文: {(model.contextWindow / 1000).toFixed(0)}K</p>
                              )}
                              {model.reasoningLevels && model.reasoningLevels.length > 0 && (
                                <p className="text-xs text-muted">
                                  思考强度: {model.reasoningLevels.join(' / ')}
                                </p>
                              )}
                            </div>
                          </div>
                          <div className="flex items-center gap-2 ml-2">
                            <button
                              onClick={() => {
                                setEditingModelId(model.id);
                                setEditingModelData({ id: model.id, contextWindow: model.contextWindow });
                              }}
                              className="text-muted hover:text-foreground text-xs"
                            >
                              编辑
                            </button>
                            <button onClick={() => handleDeleteModel(editingProvider.id, model.id)} className="text-muted hover:text-red-600 text-xs">删除</button>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                  {editingProvider.models.length === 0 && (
                    <p className="text-sm text-muted py-2">暂无模型。点击"扫描模型"自动获取，或手动添加。</p>
                  )}
                </div>
                <button onClick={() => setShowAddModelModal(true)} className="btn-editorial text-xs">+ 手动添加</button>
              </div>

              {/* Actions */}
              <div className="flex gap-4 pt-4 border-t border-border">
                <button onClick={() => handleDeleteProvider(editingProvider.id)} className="text-sm text-red-600 hover:text-red-700">删除供应商</button>
                <div className="flex-1" />
                <button onClick={() => setEditingProvider(null)} className="btn-editorial">取消</button>
                <button onClick={handleSaveEditing} className="btn-editorial-primary">保存配置</button>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center text-muted text-sm">
          选择左侧供应商进行配置
        </div>
      )}

      {/* Add Model Modal */}
      {showAddModelModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-background border border-border w-96 p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-serif text-lg">添加模型</h3>
              <button onClick={() => setShowAddModelModal(false)} className="text-muted hover:text-foreground">✕</button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="label-editorial block mb-2">模型 ID</label>
                <input type="text" value={newModelId} onChange={(e) => setNewModelId(e.target.value)} className="input-editorial" placeholder="如：gpt-4o, deepseek-chat" />
              </div>
              <div>
                <label className="label-editorial block mb-2">上下文窗口</label>
                <input type="number" value={newModelContext} onChange={(e) => setNewModelContext(Number(e.target.value))} className="input-editorial" />
              </div>
            </div>
            <div className="flex gap-4 mt-6 pt-4 border-t border-border">
              <button onClick={() => setShowAddModelModal(false)} className="btn-editorial flex-1">取消</button>
              <button onClick={handleAddModel} className="btn-editorial-primary flex-1" disabled={!newModelId}>保存</button>
            </div>
          </div>
        </div>
      )}

      {/* Add Provider Modal */}
      {showAddModal && (
        <AddProviderModal onAdd={handleAddProvider} onClose={() => setShowAddModal(false)} />
      )}
    </div>
  );
}

function AddProviderModal({ onAdd, onClose }: { onAdd: (p: Omit<Provider, 'id' | 'status'>) => void; onClose: () => void }) {
  const [name, setName] = useState('');
  const [baseUrl, setBaseUrl] = useState('https://api.openai.com/v1');
  const [apiKey, setApiKey] = useState('');
  const [apiFormat, setApiFormat] = useState<Provider['apiFormat']>('openai');

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div className="bg-background border border-border w-[32rem] p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="font-serif text-lg">添加供应商</h3>
            <p className="text-xs text-muted mt-1">通过 API 直连管理模型服务商</p>
          </div>
          <button onClick={onClose} className="text-muted hover:text-foreground">✕</button>
        </div>
        <div className="space-y-4">
          <div>
            <label className="label-editorial block mb-2">名称</label>
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} className="input-editorial" placeholder="如：OpenAI" />
          </div>
          <div>
            <label className="label-editorial block mb-2">Base URL</label>
            <input type="url" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} className="input-editorial" placeholder="https://api.openai.com/v1" />
          </div>
          <div>
            <label className="label-editorial block mb-2">API Key</label>
            <input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} className="input-editorial" placeholder="sk-..." />
          </div>
          <div>
            <label className="label-editorial block mb-2">API 格式</label>
            <select value={apiFormat} onChange={(e) => setApiFormat(e.target.value as Provider['apiFormat'])} className="input-editorial">
              <option value="openai">OpenAI Compatible (/chat/completions)</option>
              <option value="anthropic">Anthropic (/v1/messages)</option>
            </select>
          </div>
        </div>
        <div className="flex gap-4 mt-6 pt-4 border-t border-border">
          <button onClick={onClose} className="btn-editorial flex-1">取消</button>
          <button onClick={() => { if (name && baseUrl) onAdd({ name, baseUrl, apiKey, apiFormat, models: [], enabled: true }); }} className="btn-editorial-primary flex-1" disabled={!name || !baseUrl}>添加供应商</button>
        </div>
      </div>
    </div>
  );
}
