// packages/studio/src/components/book/BookCharacters.tsx
'use client';

import { api } from '@/lib/api';

import { useState, useEffect } from 'react';

interface Character {
  id: string;
  name: string;
  role: string;
  personality: string[];
  background: string;
  goals: string[];
  relationships: Record<string, string>;
  arcStage?: string;
  lastAppearance?: number;
}

export function BookCharacters({ bookId, book }: { bookId: string; book: any }) {
  const [characters, setCharacters] = useState<Character[]>(book.characters || []);
  const [showAdd, setShowAdd] = useState(false);
  const [view, setView] = useState<'cards' | 'graph'>('cards');
  const [newChar, setNewChar] = useState({ name: '', role: 'supporting', personality: '', background: '', goals: '' });

  const roleLabels: Record<string, string> = { protagonist: '主角', antagonist: '反派', supporting: '配角', minor: '路人' };

  const handleAdd = async () => {
    try {
      const char = await api.post(`/api/books/${bookId}/characters`, {
        ...newChar,
        personality: newChar.personality.split(/[,，、]/).map(s => s.trim()).filter(Boolean),
        goals: newChar.goals.split(/[,，、]/).map(s => s.trim()).filter(Boolean),
        relationships: {},
      });
      setCharacters([...characters, char]);
      setShowAdd(false);
      setNewChar({ name: '', role: 'supporting', personality: '', background: '', goals: '' });
    } catch {}
  };

  const handleDelete = async (cid: string) => {
    await api.del(`/api/books/${bookId}/characters/${cid}`);
    setCharacters(characters.filter(c => c.id !== cid));
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <p className="label-editorial text-muted">角色列表 ({characters.length})</p>
        <div className="flex gap-2">
          <button onClick={() => setView(view === 'cards' ? 'graph' : 'cards')} className="btn-editorial text-xs">{view === 'cards' ? '关系图谱' : '卡片视图'}</button>
          <button onClick={() => setShowAdd(true)} className="btn-editorial-primary text-xs">添加角色</button>
        </div>
      </div>

      {view === 'cards' ? (
        characters.length === 0 ? (
          <div className="card-editorial text-center py-12"><p className="text-muted">暂无角色</p></div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {characters.map(char => (
              <div key={char.id} className="card-editorial">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <p className="font-serif text-lg">{char.name}</p>
                    <span className="text-xs text-muted">{roleLabels[char.role] || char.role}</span>
                  </div>
                  <button onClick={() => handleDelete(char.id)} className="text-xs text-muted hover:text-red-600">删除</button>
                </div>
                {char.personality?.length > 0 && (
                  <div className="flex flex-wrap gap-1 mb-2">
                    {char.personality.map((p, i) => <span key={i} className="px-2 py-0.5 text-xs border border-border">{p}</span>)}
                  </div>
                )}
                {char.background && <p className="text-xs text-muted mb-2 line-clamp-2">{char.background}</p>}
                {char.goals?.length > 0 && (
                  <div className="text-xs text-muted">目标: {char.goals.join('、')}</div>
                )}
              </div>
            ))}
          </div>
        )
      ) : (
        <div className="card-editorial py-12 text-center">
          <p className="text-muted mb-2">关系图谱</p>
          <p className="text-xs text-muted">需要安装 react-force-graph-2d 后启用</p>
        </div>
      )}

      {showAdd && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-background border border-border w-[32rem] p-6 max-h-[80vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-serif text-lg">添加角色</h3>
              <button onClick={() => setShowAdd(false)} className="text-muted hover:text-foreground">✕</button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="label-editorial block mb-2">姓名</label>
                <input type="text" value={newChar.name} onChange={e => setNewChar({ ...newChar, name: e.target.value })} className="input-editorial" placeholder="角色姓名" />
              </div>
              <div>
                <label className="label-editorial block mb-2">角色类型</label>
                <select value={newChar.role} onChange={e => setNewChar({ ...newChar, role: e.target.value })} className="input-editorial">
                  {Object.entries(roleLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
                </select>
              </div>
              <div>
                <label className="label-editorial block mb-2">性格特征（逗号分隔）</label>
                <input type="text" value={newChar.personality} onChange={e => setNewChar({ ...newChar, personality: e.target.value })} className="input-editorial" placeholder="坚韧、隐忍、重情重义" />
              </div>
              <div>
                <label className="label-editorial block mb-2">背景故事</label>
                <textarea value={newChar.background} onChange={e => setNewChar({ ...newChar, background: e.target.value })} className="input-editorial" rows={3} placeholder="角色的背景经历..." />
              </div>
              <div>
                <label className="label-editorial block mb-2">目标（逗号分隔）</label>
                <input type="text" value={newChar.goals} onChange={e => setNewChar({ ...newChar, goals: e.target.value })} className="input-editorial" placeholder="复仇、变强、查明真相" />
              </div>
            </div>
            <div className="flex gap-4 mt-6 pt-4 border-t border-border">
              <button onClick={() => setShowAdd(false)} className="btn-editorial flex-1">取消</button>
              <button onClick={handleAdd} className="btn-editorial-primary flex-1" disabled={!newChar.name}>添加</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// packages/studio/src/lib/components/book/BookCharacters.svelte
<script>
  import { api } from '$lib/api';
  import { toasts } from '$lib/stores/toast';
  let { bookId, book } = $props();
  let characters = $derived(book?.characters || []);
  let editing = $state(null);

  function addChar() {
    editing = { id: crypto.randomUUID(), name: '', personality: '', background: '', goals: '', relationships: '' };
  }
  async function save() {
    if (!editing?.name?.trim()) return;
    try {
      await api.post(`/api/books/${bookId}/characters`, editing);
      toasts.add('角色已保存', 'success');
      editing = null;
      window.location.reload();
    } catch { toasts.add('保存失败', 'error'); }
  }
  async function del(id) {
    try {
      await api.del(`/api/books/${bookId}/characters/${id}`);
      toasts.add('已删除', 'success');
      window.location.reload();
    } catch { toasts.add('删除失败', 'error'); }
  }
</script>

<div class="space-y-3">
  <div class="flex items-center justify-between mb-4">
    <p class="text-[10px] uppercase tracking-widest text-muted">角色列表 ({characters.length})</p>
    <button onclick={addChar} class="text-xs text-muted hover:text-foreground transition-colors">+ 添加角色</button>
  </div>

  {#if characters.length === 0 && !editing}
    <p class="text-xs text-muted text-center py-8">暂无角色</p>
  {/if}

  {#each characters as c}
    <div class="border border-border p-3">
      <div class="flex items-center justify-between mb-1">
        <p class="text-sm font-medium">{c.name}</p>
        <button onclick={() => del(c.id)} class="text-[10px] text-red-500 hover:text-red-700">删除</button>
      </div>
      {#if c.personality}<p class="text-xs text-muted">{Array.isArray(c.personality) ? c.personality.join('、') : c.personality}</p>{/if}
      {#if c.background}<p class="text-xs text-muted mt-1">{c.background}</p>{/if}
    </div>
  {/each}

  {#if editing}
    <div class="border border-border p-4 space-y-3">
      <p class="text-[10px] uppercase tracking-widest text-muted">新角色</p>
      <input type="text" bind:value={editing.name} placeholder="角色名" class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" />
      <input type="text" bind:value={editing.personality} placeholder="性格（逗号分隔）" class="w-full border border-border px-3 py-2 text-sm bg-transparent focus:outline-none focus:border-foreground" />
      <textarea bind:value={editing.background} placeholder="背景故事" class="w-full border border-border px-3 py-2 text-sm bg-transparent h-20 resize-none focus:outline-none focus:border-foreground"></textarea>
      <div class="flex gap-2">
        <button onclick={save} class="bg-foreground text-background px-3 py-1.5 text-xs border border-foreground hover:bg-transparent hover:text-foreground transition-colors">保存</button>
        <button onclick={() => editing = null} class="border border-border px-3 py-1.5 text-xs hover:border-foreground transition-colors">取消</button>
      </div>
    </div>
  {/if}
</div>
