// packages/studio/src/lib/components/Toast.svelte
<script>
  import { toasts } from '$lib/stores/toast';
</script>

<div class="fixed bottom-4 left-1/2 -translate-x-1/2 z-[300] flex flex-col gap-2 pointer-events-none">
  {#each $toasts as t (t.id)}
    <div
      class="px-4 py-2 text-sm border shadow-sm pointer-events-auto transition-all {t.type === 'error'
        ? 'bg-red-50 border-red-200 text-red-800 dark:bg-red-950 dark:border-red-800 dark:text-red-200'
        : t.type === 'success'
          ? 'bg-green-50 border-green-200 text-green-800 dark:bg-green-950 dark:border-green-800 dark:text-green-200'
          : 'bg-background border-border text-foreground'}"
    >
      {t.message}
    </div>
  {/each}
</div>

// frontend/src/components/ui/Toast.tsx
import { useUIStore } from '@/stores/uiStore'
import { X, CheckCircle, AlertCircle, Info } from 'lucide-react'

const icons = {
  success: CheckCircle,
  error: AlertCircle,
  info: Info,
}

const colors = {
  success: 'border-foreground',
  error: 'border-foreground',
  info: 'border-muted',
}

export default function ToastContainer() {
  const toasts = useUIStore((s) => s.toasts)
  const removeToast = useUIStore((s) => s.removeToast)

  if (toasts.length === 0) return null

  return (
    <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 flex flex-col gap-2">
      {toasts.map((t) => {
        const Icon = icons[t.type]
        return (
          <div
            key={t.id}
            className={`flex items-center gap-3 border ${colors[t.type]} bg-background px-4 py-3 text-sm min-w-[280px]`}
          >
            <Icon size={14} className="shrink-0" />
            <span className="flex-1">{t.message}</span>
            <button
              onClick={() => removeToast(t.id)}
              className="shrink-0 p-0.5 hover:bg-foreground/5"
            >
              <X size={12} />
            </button>
          </div>
        )
      })}
    </div>
  )
}
