// packages/studio/src/app/(dashboard)/agents/page.tsx
'use client';

import { api } from '@/lib/api';

import { useState, useEffect } from 'react';

interface AgentStatus {
  role: string;
  name: string;
  nameZh: string;
  category: string;
  model: string;
  enabled: boolean;
}

const AGENT_META: Record<string, { name: string; nameZh: string; category: string }> = {
  architect: { name: 'Architect', nameZh: '故事架构师', category: '核心创作' },
  writer: { name: 'Writer', nameZh: '写作特工', category: '核心创作' },
  'character-intelligence': { name: 'Character Intelligence', nameZh: '角色智能体', category: '核心创作' },
  reviewer: { name: 'Reviewer', nameZh: '审阅官', category: '质量控制' },
  editor: { name: 'Editor', nameZh: '编辑', category: '质量控制' },
  'de-ai-editor': { name: 'De-AI Editor', nameZh: '去AI味编辑', category: '质量控制' },
  'fact-checker': { name: 'Fact Checker', nameZh: '事实核查官', category: '质量控制' },
  continuity: { name: 'Continuity', nameZh: '连续性检查官', category: '质量控制' },
  'pacing-controller': { name: 'Pacing Controller', nameZh: '节奏控制官', category: '质量控制' },
  'style-analyzer': { name: 'Style Analyzer', nameZh: '风格分析师', category: '辅助' },
  observer: { name: 'Observer', nameZh: '观察者', category: '辅助' },
  'character-designer': { name: 'Character Designer', nameZh: '角色设计师', category: '辅助' },
  foreshadowing: { name: 'Foreshadowing', nameZh: '伏笔管理官', category: '辅助' },
  radar: { name: 'Radar', nameZh: '趋势雷达', category: '辅助' },
  reflector: { name: 'Reflector', nameZh: '反思官', category: '辅助' },
};

export default function AgentsPage() {
  const [agents, setAgents] = useState<AgentStatus[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/api/config?type=agents')
      .then(data => {
        const configs = data.agents || [];
        const agentList: AgentStatus[] = configs.map((c: any) => {
          const meta = AGENT_META[c.role] || { name: c.name || c.role, nameZh: c.nameZh || c.role, category: '其他' };
          return {
            role: c.role,
            name: meta.name,
            nameZh: meta.nameZh,
            category: meta.category,
            model: c.modelId || '未配置',
            enabled: c.enabled !== false,
          };
        });
        setAgents(agentList);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const categories = [...new Set(agents.map(a => a.category))];

  if (loading) {
    return (
      <div>
        <header className="mb-8 px-12 pt-6">
          <h2 className="font-serif text-2xl tracking-tight">Agent 监控</h2>
          <p className="text-muted text-sm mt-1">加载中...</p>
        </header>
      </div>
    );
  }

  return (
    <div>
      <header className="mb-8 px-12 pt-6">
        <h2 className="font-serif text-2xl tracking-tight">Agent 监控</h2>
        <p className="text-muted text-sm mt-1">监控所有Agent的状态和性能</p>
      </header>

      <div className="px-12 pb-12">
        {/* Summary Stats */}
        <div className="grid grid-cols-3 gap-6 mb-12">
          <div className="card-editorial">
            <p className="label-editorial text-muted">总Agent数</p>
            <p className="font-serif text-3xl mt-2">{agents.length}</p>
          </div>
          <div className="card-editorial">
            <p className="label-editorial text-muted">已启用</p>
            <p className="font-serif text-3xl mt-2">{agents.filter(a => a.enabled).length}</p>
          </div>
          <div className="card-editorial">
            <p className="label-editorial text-muted">已禁用</p>
            <p className="font-serif text-3xl mt-2">{agents.filter(a => !a.enabled).length}</p>
          </div>
        </div>

        {/* Agent Groups */}
        {categories.map(category => (
          <section key={category} className="mb-12">
            <h3 className="label-editorial text-muted mb-4">{category}</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
              {agents.filter(a => a.category === category).map(agent => (
                <div
                  key={agent.role}
                  className={`card-editorial block ${!agent.enabled ? 'opacity-50' : ''}`}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="font-sans text-sm font-medium">{agent.nameZh}</p>
                      <p className="font-mono text-xs text-muted">{agent.name}</p>
                    </div>
                    <div className={`w-2 h-2 rounded-full ${agent.enabled ? 'bg-green-500' : 'bg-muted'}`} />
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-muted">模型</span>
                      <span className="font-mono text-xs text-muted truncate ml-2">{agent.model}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-muted">状态</span>
                      <span className={`text-xs ${agent.enabled ? 'text-foreground' : 'text-muted'}`}>
                        {agent.enabled ? '已启用' : '已禁用'}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}

// packages/studio/src/routes/(app)/agents/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { api } from '$lib/api';

  const AGENT_META = {
    architect: { name: 'Architect', nameZh: '故事架构师', category: '核心创作' },
    writer: { name: 'Writer', nameZh: '写作特工', category: '核心创作' },
    'character-intelligence': { name: 'Character Intelligence', nameZh: '角色智能体', category: '核心创作' },
    reviewer: { name: 'Reviewer', nameZh: '审阅官', category: '质量控制' },
    editor: { name: 'Editor', nameZh: '编辑', category: '质量控制' },
    'de-ai-editor': { name: 'De-AI Editor', nameZh: '去AI味编辑', category: '质量控制' },
    'fact-checker': { name: 'Fact Checker', nameZh: '事实核查官', category: '质量控制' },
    continuity: { name: 'Continuity', nameZh: '连续性检查官', category: '质量控制' },
    'pacing-controller': { name: 'Pacing Controller', nameZh: '节奏控制官', category: '质量控制' },
    'style-analyzer': { name: 'Style Analyzer', nameZh: '风格分析师', category: '辅助' },
    observer: { name: 'Observer', nameZh: '观察者', category: '辅助' },
    'character-designer': { name: 'Character Designer', nameZh: '角色设计师', category: '辅助' },
    foreshadowing: { name: 'Foreshadowing', nameZh: '伏笔管理官', category: '辅助' },
    radar: { name: 'Radar', nameZh: '趋势雷达', category: '辅助' },
    reflector: { name: 'Reflector', nameZh: '反思官', category: '辅助' },
  };

  let agents = $state([]);
  let loading = $state(true);

  onMount(async () => {
    try {
      const data = await api.get('/api/config?type=agents');
      const configs = data.agents || [];
      agents = configs.map(c => ({
        ...c,
        ...(AGENT_META[c.role] || { name: c.name, nameZh: c.nameZh, category: '其他' }),
      }));
    } catch {}
    loading = false;
  });

  let categories = $derived([...new Set(agents.map(a => AGENT_META[a.role]?.category || '其他'))]);
</script>

<div class="p-8">
  <h1 class="font-serif text-xl tracking-tight mb-6">Agent 监控</h1>

  {#if loading}
    <p class="text-sm text-muted">加载中...</p>
  {:else}
    <div class="grid grid-cols-3 gap-4 mb-6">
      <div class="border border-border p-4 text-center">
        <p class="font-mono text-2xl">{agents.length}</p>
        <p class="text-xs text-muted">已配置</p>
      </div>
      <div class="border border-border p-4 text-center">
        <p class="font-mono text-2xl">{agents.filter(a => a.enabled !== false).length}</p>
        <p class="text-xs text-muted">已启用</p>
      </div>
      <div class="border border-border p-4 text-center">
        <p class="font-mono text-2xl">{agents.filter(a => a.enabled === false).length}</p>
        <p class="text-xs text-muted">已禁用</p>
      </div>
    </div>

    {#each [...new Set(agents.map(a => AGENT_META[a.role]?.category || '其他'))] as category}
      <div class="mb-6">
        <p class="text-[10px] uppercase tracking-widest text-muted mb-3">{category}</p>
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3">
          {#each agents.filter(a => (AGENT_META[a.role]?.category || '其他') === category) as agent}
            <div class="border border-border p-3 {agent.enabled === false ? 'opacity-50' : ''}">
              <div class="flex items-start justify-between mb-2">
                <div>
                  <p class="text-sm font-medium">{agent.nameZh || agent.role}</p>
                  <p class="text-[10px] text-muted font-mono">{agent.name || agent.role}</p>
                </div>
                <span class="w-2 h-2 rounded-full {agent.enabled !== false ? 'bg-green-500' : 'bg-muted/30'}"></span>
              </div>
              <p class="text-[10px] text-muted">模型: {agent.modelId || '未配置'}</p>
            </div>
          {/each}
        </div>
      </div>
    {/each}
  {/if}
</div>
